### ISSUE TITLE
Introducing gradle and eselect-gradle to Gentoo stable tree

### ISSUE THREAD

**Issue by archenroot** [doctaweeks/junkdrawer-overlay#1]
Hi,

I think gradle and eselect-gradle are nice extensions for Java ecosystem in Gentoo, I will raise a request at bugs.gentoo.org.

Thanks for your work.

**Comment by archenroot** [comment]
Oh, I realized now both packages are in official Java overlay included, so not required to make this transition in the moment.

**Comment by doctaweeks** [comment]
Correct, eselect-gradle is from the java overlay. The gradle source versions in the java overlay are quite old but there are some more recent -bin variants. I keep more recent source versions in my overlay.
