### ISSUE TITLE
checksum failure in media-libs/woff2

### ISSUE THREAD

**Issue by ckonstanski** [doctaweeks/junkdrawer-overlay#2]
Action: sync for repo: junkdrawer, returned code = 0
!!! Manifest verification failed:
Manifest mismatch for media-libs/woff2/Manifest
  __size__: expected: 904, have: 901

**Comment by doctaweeks** [comment]
This package has never been in the junkdrawer. Please double check where this error occurred.

**Comment by ckonstanski** [comment]
You're right, sorry. I ran emaint sync -a via ansible and it moved output around. Maybe it put stderr at the end or something. It's in the main tree.
