### ISSUE TITLE
x11-misc/virtualgl/virtualgl-9999.ebuild EAPI=5 is not supported

### ISSUE THREAD

**Issue by perestoronin** [doctaweeks/junkdrawer-overlay#4]
https://github.com/doctaweeks/junkdrawer-overlay/blob/master/x11-misc/virtualgl/virtualgl-9999.ebuild

has bug: EAPI=5 is not supported

To fix: set EAPI=6  or remove obsolete ebuild

**Comment by doctaweeks** [comment]
Resolved by 6f66e3b3ddc21798b3159b2446fe18b16f97ebe5
